apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: nour-app
spec:
  secretStoreRef:
    name: ClusterSecretStore
    kind: nour-kv-test
  refreshInterval: 5m
  data:
    - secretKey: USERNAME
      remoteRef: 
        key: username
    - secretKey: PASSWORD
      remoteRef: 
        key: password
  target:
    name: nour-app
    deletionPolicy: Delete