---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nour-helm-app1
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 10s
  targetNamespace: default
  values:
    image:
      pullPolicy: IfNotPresent
      repository: nginx
      tag: 1.14.2
    labels:
      app: nginx
    replicas: 3
    service:
      port: 80
